const carRentalData = [
    // --- SEDANS ---
    {
        "id": 1,
        "name": "Maruti Swift Dzire",
        "type": "Sedan",
        "seats": 4,
        "bags": 2,
        "ac": true,
        "price_per_km": 12,
        "price_per_day": 3000,
        "rate_unit": "/ km",
        "min_daily_km": 250,
        "driver_allowance": 400,
        "image": "https://imgd.aeplcdn.com/1056x594/n/cw/ec/45691/swift-dzire-exterior-right-front-three-quarter-3.jpeg?q=75",
        "rating": 4.8,
        "description": "Most popular compact sedan for city and outstation trips.",
        "features": ["AC", "Music System", "Comfortable Seats", "Boot Space"]
    },
    {
        "id": 2,
        "name": "Toyota Etios",
        "type": "Sedan",
        "seats": 4,
        "bags": 3,
        "ac": true,
        "price_per_km": 12,
        "price_per_day": 3200,
        "rate_unit": "/ km",
        "min_daily_km": 250,
        "driver_allowance": 400,
        "image": "https://imgd.aeplcdn.com/1056x594/n/cw/ec/26532/platinum-etios-exterior-right-front-three-quarter-56455.jpeg?q=75",
        "rating": 4.7,
        "description": "Spacious sedan known for its reliability and large boot space.",
        "features": ["AC", "Spacious Boot", "Legroom", "Safety Airbags"]
    },
    {
        "id": 201,
        "name": "Hyundai Aura",
        "type": "Sedan",
        "seats": 4,
        "bags": 2,
        "ac": true,
        "price_per_km": 12,
        "price_per_day": 3000,
        "rate_unit": "/ km",
        "min_daily_km": 250,
        "driver_allowance": 400,
        "image": "https://imgd.aeplcdn.com/1056x594/n/cw/ec/139317/aura-exterior-right-front-three-quarter-37.jpeg?isig=0&q=75",
        "rating": 4.6,
        "description": "Modern compact sedan with premium interiors.",
        "features": ["AC", "Rear Vents", "Bluetooth Audio", "Charging Ports"]
    },
    {
        "id": 202,
        "name": "Honda Amaze",
        "type": "Sedan",
        "seats": 4,
        "bags": 3,
        "ac": true,
        "price_per_km": 13,
        "price_per_day": 3500,
        "rate_unit": "/ km",
        "min_daily_km": 250,
        "driver_allowance": 400,
        "image": "https://imgd.aeplcdn.com/1056x594/n/cw/ec/45951/amaze-exterior-right-front-three-quarter-3.jpeg?q=75",
        "rating": 4.8,
        "description": "Premium sedan experience with smooth ride quality.",
        "features": ["AC", "Climate Control", "Armrest", "Smooth Ride"]
    },

    // --- SUVs ---
    {
        "id": 3,
        "name": "Maruti Ertiga",
        "type": "SUV",
        "seats": 7,
        "bags": 3,
        "ac": true,
        "price_per_km": 15,
        "price_per_day": 4500,
        "rate_unit": "/ km",
        "min_daily_km": 250,
        "driver_allowance": 400,
        "image": "https://imgd.aeplcdn.com/1056x594/n/cw/ec/115609/ertiga-exterior-right-front-three-quarter-11.jpeg?isig=0&q=75",
        "rating": 4.7,
        "description": "Smart hybrid MUV, excellent for budget group travel.",
        "features": ["AC", "Reclining Seats", "Roof Blower", "CNG Option"]
    },
    {
        "id": 4,
        "name": "Toyota Innova",
        "type": "SUV",
        "seats": 7,
        "bags": 4,
        "ac": true,
        "price_per_km": 18,
        "price_per_day": 5000,
        "rate_unit": "/ km",
        "min_daily_km": 250,
        "driver_allowance": 400,
        "image": "https://imgd.aeplcdn.com/1056x594/n/cw/ec/140809/innova-crysta-exterior-right-front-three-quarter-2.jpeg?isig=0&q=75",
        "rating": 4.8,
        "description": "Reliable and spacious SUV for long distance travel.",
        "features": ["AC", "Captain Seats", "Safety Airbags", "Music System"]
    },
    {
        "id": 203,
        "name": "Mahindra Scorpio N",
        "type": "SUV",
        "seats": 7,
        "bags": 4,
        "ac": true,
        "price_per_km": 18,
        "price_per_day": 5500,
        "rate_unit": "/ km",
        "min_daily_km": 250,
        "driver_allowance": 400,
        "image": "https://imgd.aeplcdn.com/1056x594/n/cw/ec/40432/scorpio-n-exterior-right-front-three-quarter-75.jpeg?isig=0&q=75",
        "rating": 4.8,
        "description": "Rugged yet premium. Perfect for hill stations.",
        "features": ["4x4 Capable", "High Ground Clearance", "Power Styling", "Sunroof"]
    },
    {
        "id": 204,
        "name": "Mahindra XUV700",
        "type": "SUV",
        "seats": 7,
        "bags": 4,
        "ac": true,
        "price_per_km": 20,
        "price_per_day": 6000,
        "rate_unit": "/ km",
        "min_daily_km": 250,
        "driver_allowance": 400,
        "image": "https://imgd.aeplcdn.com/1056x594/n/cw/ec/42355/xuv700-exterior-right-front-three-quarter-3.jpeg?isig=0&q=75",
        "rating": 4.9,
        "description": "Tech-loaded luxury SUV with panoramic viewing experience.",
        "features": ["Skyroof", "ADAS Safety", "Premium Audio", "Leatherette"]
    },

    // --- LUXURY SUVs ---
    {
        "id": 5,
        "name": "Toyota Innova Crysta",
        "type": "Luxury SUV",
        "seats": 7,
        "bags": 4,
        "ac": true,
        "price_per_km": 22, // Reduced from 24
        "price_per_day": 6500,
        "rate_unit": "/ km",
        "min_daily_km": 250,
        "driver_allowance": 400,
        "image": "https://imgd.aeplcdn.com/1056x594/n/cw/ec/140809/innova-crysta-exterior-right-front-three-quarter-2.jpeg?isig=0&q=75",
        "rating": 5.0,
        "description": "Premium comfort with powerful performance and luxury interiors.",
        "features": ["Leather Seats", "Ambience Lighting", "Climate Control", "Cruise Control"]
    },
    {
        "id": 161,
        "name": "Toyota Innova Hycross",
        "type": "Luxury SUV",
        "seats": 7,
        "bags": 4,
        "ac": true,
        "price_per_km": 26, // Reduced from 28
        "price_per_day": 7000,
        "rate_unit": "/ km",
        "min_daily_km": 250,
        "driver_allowance": 500,
        "image": "https://imgd.aeplcdn.com/1056x594/n/cw/ec/135759/innova-hycross-exterior-right-front-three-quarter-112.jpeg?isig=0&q=75",
        "rating": 5.0,
        "description": "New hybrid technology with ultra-premium interiors and silence.",
        "features": ["Hybrid Quiet", "Sunroof", "Ottoman Seats", "Mood Lighting"]
    },
    {
        "id": 6,
        "name": "Toyota Fortuner",
        "type": "Luxury SUV",
        "seats": 7,
        "bags": 4,
        "ac": true,
        "price_per_km": 28, // Reduced from 30
        "price_per_day": 8500,
        "rate_unit": "/ km",
        "min_daily_km": 250,
        "driver_allowance": 500,
        "image": "https://imgd.aeplcdn.com/1056x594/n/cw/ec/44709/fortuner-exterior-right-front-three-quarter-20.jpeg?q=75",
        "rating": 5.0,
        "description": "Dominating presence with 4x4 capability and luxury features.",
        "features": ["4x4", "Sunroof", "Premium Audio", "Leather Interiors"]
    },

    // --- TEMPO TRAVELLERS ---
    {
        "id": 7,
        "name": "Tempo Traveller (12 Seater)",
        "type": "Tempo",
        "seats": 12,
        "bags": 8,
        "ac": true,
        "price_per_km": 24, // Adjusted
        "price_per_day": 7500,
        "rate_unit": "/ km",
        "min_daily_km": 300,
        "driver_allowance": 500,
        "image": "https://files.prokerala.com/news/photos/imgs/1024/a-tempo-traveller-that-fell-into-a-gorge-killing-1327103.jpg",
        "rating": 4.8,
        "description": "Ideal for medium groups. Comfortable pushback seats.",
        "features": ["AC", "Pushback Seats", "Music System", "Curtains"]
    },
    {
        "id": 8,
        "name": "Tempo Traveller (17 Seater)",
        "type": "Tempo",
        "seats": 17,
        "bags": 10,
        "ac": true,
        "price_per_km": 26,
        "price_per_day": 9000,
        "rate_unit": "/ km",
        "min_daily_km": 300,
        "driver_allowance": 600,
        "image": "https://st.depositphotos.com/1004114/2550/i/950/depositphotos_25506045-stock-photo-white-minibus.jpg",
        "rating": 4.9,
        "description": "Spacious traveller for larger groups with ample luggage space.",
        "features": ["Individual AC", "Reading Lights", "Reclining Seats", "Wide Aisle"]
    },
    {
        "id": 206,
        "name": "Force Urbania (17 Seater)",
        "type": "Tempo",
        "seats": 17,
        "bags": 10,
        "ac": true,
        "price_per_km": 30, // Reduced from 35
        "price_per_day": 12000,
        "rate_unit": "/ km",
        "min_daily_km": 300,
        "driver_allowance": 700,
        "image": "https://st.depositphotos.com/1004114/2550/i/950/depositphotos_25506045-stock-photo-white-minibus.jpg",
        "rating": 5.0,
        "description": "Next-gen luxury traveller. Best in class comfort and aesthetics.",
        "features": ["Individual AC Vents", "Reclining Seats", "Reading Lights", "Air Suspension"]
    },
    {
        "id": 9,
        "name": "Tempo Traveller (20 Seater)",
        "type": "Tempo",
        "seats": 20,
        "bags": 12,
        "ac": true,
        "price_per_km": 30,
        "price_per_day": 11000,
        "rate_unit": "/ km",
        "min_daily_km": 300,
        "driver_allowance": 600,
        "image": "https://5.imimg.com/data5/SELLER/Default/2022/9/OL/QG/CF/2626689/26-seater-tempo-traveller-rental-service-500x500.jpg",
        "rating": 4.7,
        "description": "Perfect for corporate groups and extended families.",
        "features": ["2x1 Seating", "Sound System", "Charging Points", "Luggage Carrier"]
    },
    {
        "id": 10,
        "name": "Tempo Traveller (26 Seater)",
        "type": "Tempo",
        "seats": 26,
        "bags": 15,
        "ac": true,
        "price_per_km": 33,
        "price_per_day": 14000,
        "rate_unit": "/ km",
        "min_daily_km": 300,
        "driver_allowance": 600,
        "image": "https://5.imimg.com/data5/SELLER/Default/2022/9/OL/QG/CF/2626689/26-seater-tempo-traveller-rental-service-500x500.jpg",
        "rating": 4.6,
        "description": "Mini-bus style comfort for large groups.",
        "features": ["2x2 Seating", "Spacious Interior", "PA System", "Comfortable Ride"]
    },

    // --- LUXURY CARS ---
    {
        "id": 207,
        "name": "Audi A6",
        "type": "Luxury",
        "seats": 4,
        "bags": 3,
        "ac": true,
        "price_per_km": 90,
        "price_per_day": 25000,
        "rate_unit": "/ km",
        "min_daily_km": 200,
        "driver_allowance": 1000,
        "image": "https://imgd.aeplcdn.com/1056x594/n/cw/ec/41443/a6-exterior-right-front-three-quarter-3.jpeg?q=75",
        "rating": 5.0,
        "description": "Executive luxury sedan for weddings and corporate delegates.",
        "features": ["Matrix LED", "Virtual Cockpit", "Bang & Olufsen Audio", "Massage Seats"]
    },
    {
        "id": 208,
        "name": "BMW 5 Series",
        "type": "Luxury",
        "seats": 4,
        "bags": 3,
        "ac": true,
        "price_per_km": 100,
        "price_per_day": 28000,
        "rate_unit": "/ km",
        "min_daily_km": 200,
        "driver_allowance": 1200,
        "image": "https://imgd.aeplcdn.com/1056x594/n/cw/ec/151975/5-series-exterior-right-front-three-quarter-4.jpeg?isig=0&q=75",
        "rating": 5.0,
        "description": "The ultimate driving machine. Unparalleled status symbol.",
        "features": ["Gesture Control", "Sunroof", "Premium Leather", "Chauffeur Drive"]
    },
    {
        "id": 209,
        "name": "Mercedes Benz C-Class",
        "type": "Luxury",
        "seats": 4,
        "bags": 3,
        "ac": true,
        "price_per_km": 95,
        "price_per_day": 26000,
        "rate_unit": "/ km",
        "min_daily_km": 200,
        "driver_allowance": 1200,
        "image": "https://imgd.aeplcdn.com/1056x594/n/cw/ec/116241/c-class-exterior-right-front-three-quarter-3.jpeg?isig=0&q=75",
        "rating": 5.0,
        "description": "Sophisticated luxury with the three-pointed star legacy.",
        "features": ["Ambient Lighting", "Burmester Sound", "Panoramic Sunroof", "Recliner"]
    },

    // --- BUSES ---
    {
        "id": 11,
        "name": "Mini Bus (26 Seater)",
        "type": "Bus",
        "seats": 26,
        "bags": 20,
        "ac": false,
        "price_per_km": 16000, // Fixed day rate
        "price_per_day": 16000,
        "rate_unit": "/ Day",
        "min_daily_km": 0,
        "driver_allowance": 0,
        "image": "https://5.imimg.com/data5/ANDROID/Default/2021/1/KL/XK/XO/3757270/product-jpeg-500x500.jpg",
        "rating": 4.5,
        "description": "Economical choice for large group excursions.",
        "features": ["Pushback Seats", "Ample Luggage", "Stereo", "First Aid"]
    },
    {
        "id": 12,
        "name": "Deluxe Bus (35 Seater)",
        "type": "Bus",
        "seats": 35,
        "bags": 30,
        "ac": true,
        "price_per_km": 21000,
        "price_per_day": 21000,
        "rate_unit": "/ Day",
        "min_daily_km": 0,
        "driver_allowance": 0,
        "image": "https://cpimg.tistatic.com/05471905/b/4/Deluxe-Bus-Rental-Service.jpg",
        "rating": 4.6,
        "description": "Comfortable bus for weddings and long tours.",
        "features": ["AC", "Video Coach", "Air Suspension", "Reading Lights"]
    },
    {
        "id": 13,
        "name": "Luxury Coach (45 Seater)",
        "type": "Bus",
        "seats": 45,
        "bags": 40,
        "ac": true,
        "price_per_km": 30000,
        "price_per_day": 30000,
        "rate_unit": "/ Day",
        "min_daily_km": 0,
        "driver_allowance": 0,
        "image": "https://img.staticmb.com/mbcontent/images/crop/uploads/2022/6/Bus-dimensions_0_1200.jpg",
        "rating": 4.8,
        "description": "Premium Volvo/Mercedes coach for ultimate group luxury.",
        "features": ["Volvo/Scania", "Toilet (Optional)", "Wifi", "Reclining Seats"]
    }
];

const routeDistances = [
    { route: "Kolkata ⇄ Gangasagar", oneWay: 105, roundTrip: "210 – 230" },
    { route: "Kolkata ⇄ Digha", oneWay: 185, roundTrip: "370 – 400" },
    { route: "Kolkata ⇄ Mandarmani", oneWay: 180, roundTrip: "360 – 380" },
    { route: "Kolkata ⇄ Tajpur", oneWay: 190, roundTrip: "380 – 400" },
    { route: "Kolkata ⇄ Shankarpur", oneWay: 170, roundTrip: "340 – 360" },
    { route: "Kolkata ⇄ Bakkhali", oneWay: 130, roundTrip: "260 – 280" },
    { route: "Kolkata ⇄ Henry Island", oneWay: 140, roundTrip: "280 – 300" },
    { route: "Kolkata ⇄ Sundarbans", oneWay: 110, roundTrip: "220 – 250" },
    { route: "Kolkata ⇄ Santiniketan", oneWay: 165, roundTrip: "330 – 350" },
    { route: "Kolkata ⇄ Bishnupur", oneWay: 150, roundTrip: "300 – 320" },
    { route: "Kolkata ⇄ Murshidabad", oneWay: 200, roundTrip: "400 – 420" },
    { route: "Kolkata ⇄ Mayapur", oneWay: 135, roundTrip: "270 – 290" },
    { route: "Kolkata ⇄ Tarapith", oneWay: 240, roundTrip: "480 – 500" },
    { route: "Kolkata ⇄ Bakreshwar", oneWay: 255, roundTrip: "510 – 530" },
    { route: "Kolkata ⇄ Howrah Station", oneWay: 15, roundTrip: "30 – 40" },
    { route: "Kolkata ⇄ Sealdah Station", oneWay: 10, roundTrip: "20 – 30" },
    { route: "Kolkata ⇄ Kharagpur Station", oneWay: 115, roundTrip: "230 – 250" },
    { route: "Kolkata ⇄ Malda Town Station", oneWay: 340, roundTrip: "680 – 700" },
    { route: "Kolkata ⇄ Asansol Station", oneWay: 205, roundTrip: "410 – 430" },
    { route: "Kolkata ⇄ Durgapur Station", oneWay: 175, roundTrip: "350 – 370" },
    { route: "Kolkata ⇄ CCU Airport", oneWay: 20, roundTrip: "40 – 50" },
    { route: "Kolkata ⇄ Bagdogra Airport", oneWay: 560, roundTrip: "1120 – 1150" },
    { route: "Siliguri ⇄ Darjeeling", oneWay: 70, roundTrip: "140 – 150" },
    { route: "Siliguri ⇄ Kalimpong", oneWay: 75, roundTrip: "150 – 160" },
    { route: "Siliguri ⇄ Mirik", oneWay: 55, roundTrip: "110 – 120" },
    { route: "Siliguri ⇄ Kurseong", oneWay: 50, roundTrip: "100 – 110" },
    { route: "Siliguri ⇄ Lava", oneWay: 110, roundTrip: "220 – 230" },
    { route: "Siliguri ⇄ Lolegaon", oneWay: 125, roundTrip: "250 – 260" },
    { route: "Siliguri ⇄ Lataguri", oneWay: 95, roundTrip: "190 – 200" },
    { route: "Siliguri ⇄ Jaldapara", oneWay: 135, roundTrip: "270 – 280" },
    { route: "Siliguri ⇄ Buxa", oneWay: 180, roundTrip: "360 – 380" },
    { route: "Siliguri ⇄ Dooars Circuit", oneWay: 0, roundTrip: "300 – 350" }, // 0 for variable/undefined simple one-way
    { route: "Darjeeling ⇄ Tiger Hill", oneWay: 12, roundTrip: "25 – 30" },
    { route: "Darjeeling ⇄ Mirik", oneWay: 50, roundTrip: "100 – 110" },
    { route: "Darjeeling ⇄ Kalimpong", oneWay: 50, roundTrip: "100 – 110" },
    { route: "Kalimpong ⇄ Lava", oneWay: 35, roundTrip: "70 – 80" },
    { route: "Lava ⇄ Lolegaon", oneWay: 25, roundTrip: "50 – 60" },
    { route: "Mirik ⇄ Pasupati Nagar", oneWay: 25, roundTrip: "50 – 60" },
    { route: "Kolkata ⇄ Siliguri", oneWay: 560, roundTrip: "1120 – 1150" },
    { route: "Kolkata ⇄ Darjeeling", oneWay: 630, roundTrip: "1250 – 1300" },
    { route: "Kolkata ⇄ Malda", oneWay: 340, roundTrip: "680 – 700" },
    { route: "Kolkata ⇄ Raiganj", oneWay: 400, roundTrip: "800 – 820" },
    { route: "Kolkata ⇄ Jalpaiguri", oneWay: 540, roundTrip: "1080 – 1100" }
];
