-- Poll Hub schema for Supabase
-- Run in Supabase SQL Editor.

create table if not exists public.poll_votes (
  id bigint generated by default as identity primary key,
  poll_id text not null,
  option_id text not null,
  voter_token text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists poll_votes_poll_voter_uidx
  on public.poll_votes (poll_id, voter_token);

create index if not exists poll_votes_poll_idx
  on public.poll_votes (poll_id);

create table if not exists public.poll_vote_totals (
  poll_id text not null,
  option_id text not null,
  votes bigint not null default 0,
  primary key (poll_id, option_id)
);

create index if not exists poll_vote_totals_poll_idx
  on public.poll_vote_totals (poll_id);

insert into public.poll_vote_totals (poll_id, option_id, votes)
select poll_id, option_id, count(*)::bigint
from public.poll_votes
group by poll_id, option_id
on conflict (poll_id, option_id) do update
  set votes = excluded.votes;

create table if not exists public.poll_comments (
  id bigint generated by default as identity primary key,
  poll_id text not null,
  author text not null default 'Guest',
  comment_text text not null,
  visitor_token text,
  created_at timestamptz not null default now()
);

create index if not exists poll_comments_poll_idx
  on public.poll_comments (poll_id, created_at desc);

create table if not exists public.poll_ideas (
  id bigint generated by default as identity primary key,
  question text not null,
  category text not null,
  options jsonb not null default '[]'::jsonb,
  author text not null default 'Anonymous',
  status text not null default 'pending',
  visitor_token text not null,
  created_at timestamptz not null default now()
);

create index if not exists poll_ideas_token_idx
  on public.poll_ideas (visitor_token, created_at desc);

alter table public.poll_votes enable row level security;
alter table public.poll_vote_totals enable row level security;
alter table public.poll_comments enable row level security;
alter table public.poll_ideas enable row level security;

drop policy if exists poll_votes_select_policy on public.poll_votes;
create policy poll_votes_select_policy
  on public.poll_votes
  for select
  using (true);

drop policy if exists poll_votes_insert_policy on public.poll_votes;
create policy poll_votes_insert_policy
  on public.poll_votes
  for insert
  with check (true);

drop policy if exists poll_vote_totals_select_policy on public.poll_vote_totals;
create policy poll_vote_totals_select_policy
  on public.poll_vote_totals
  for select
  using (true);

drop policy if exists poll_comments_select_policy on public.poll_comments;
create policy poll_comments_select_policy
  on public.poll_comments
  for select
  using (true);

drop policy if exists poll_comments_insert_policy on public.poll_comments;
create policy poll_comments_insert_policy
  on public.poll_comments
  for insert
  with check (true);

drop policy if exists poll_ideas_select_policy on public.poll_ideas;
create policy poll_ideas_select_policy
  on public.poll_ideas
  for select
  using (true);

drop policy if exists poll_ideas_insert_policy on public.poll_ideas;
create policy poll_ideas_insert_policy
  on public.poll_ideas
  for insert
  with check (true);

create or replace function public.cast_poll_vote(
  p_poll_id text,
  p_option_id text,
  p_voter_token text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_count int := 0;
begin
  if coalesce(trim(p_poll_id),'') = '' or coalesce(trim(p_option_id),'') = '' or coalesce(trim(p_voter_token),'') = '' then
    return jsonb_build_object('inserted', false, 'reason', 'invalid_input');
  end if;

  insert into public.poll_votes (poll_id, option_id, voter_token)
  values (p_poll_id, p_option_id, p_voter_token)
  on conflict (poll_id, voter_token) do nothing;

  get diagnostics inserted_count = row_count;
  if inserted_count = 0 then
    return jsonb_build_object('inserted', false, 'reason', 'already_voted');
  end if;

  insert into public.poll_vote_totals (poll_id, option_id, votes)
  values (p_poll_id, p_option_id, 1)
  on conflict (poll_id, option_id) do update
    set votes = public.poll_vote_totals.votes + 1;

  return jsonb_build_object('inserted', true);
end;
$$;

grant select, insert on public.poll_votes to anon, authenticated;
grant select on public.poll_vote_totals to anon, authenticated;
grant select, insert on public.poll_comments to anon, authenticated;
grant select, insert on public.poll_ideas to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
grant execute on function public.cast_poll_vote(text, text, text) to anon, authenticated;
